const { SlashCommandBuilder, EmbedBuilder } = require('discord.js');

module.exports = {
    // Main server command
    serverDescription: "Comprehensive server information and management commands",
    
    // Subcommand descriptions
    serverInfoDescription: "Show detailed server information with advanced pagination",
    serverIconDescription: "Display the server icon in high quality",
    serverBannerDescription: "Show the server banner if available",
    serverMembercountDescription: "Detailed member statistics and analytics",
    serverRolesDescription: "Complete list of server roles with details",
    serverEmojisDescription: "Display all server emojis categorized",
    serverChannelsDescription: "Comprehensive channel summary and statistics",
    serverBoostsDescription: "Server boost information and perks",
    serverRegionDescription: "Server region and locale information",
    serverVerificationDescription: "Current verification level details",
    serverFeaturesDescription: "All enabled server features and capabilities",

    // Error messages
    serverErrorTitle: "❌ **ERROR**",
    serverErrorColor: "#ff4757",
    serverErrorDescription: "``````",
    serverInfoErrorDescription: "``````",

    // Colors
    serverInfoColor: "#00d4ff",
    serverIconColor: "#7c3aed",
    serverIconNoIconColor: "#ff6b6b",
    serverBannerColor: "#00d4ff",
    serverBannerNoBannerColor: "#ff6b6b",
    serverMembercountColor: "#00bfff",
    serverRolesColor: "#8e44ad",
    serverEmojisColor: "#f39c12",
    serverChannelsColor: "#2ecc71",
    serverBoostsColor: "#ff73fa",
    serverRegionColor: "#95a5a6",
    serverVerificationColor: "#3498db",
    serverFeaturesColor: "#3498db",
    serverHelpColor: "#7289da",

    // Server Info command
    serverInfoTitle: "🏰 **SERVER INFORMATION**",
    serverInfoEmbedDescription: `\`\`\`\n🏰 SERVER ANALYTICS DASHBOARD\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\``,
    serverInfoNameField: "📛 **Server Name**",
    serverInfoNameValue: "🏷️ Identity",
    serverInfoOwnerField: "👑 **Owner**",
    serverInfoOwnerValue: "🎯 Administrator",
    serverInfoIdField: "🆔 **Server ID**",
    serverInfoIdValue: "🔢 Unique",
    serverInfoMembersField: "👥 **Total Members**",
    serverInfoMembersValue: "📈 Community",
    serverInfoBotsField: "🤖 **Bot Count**",
    serverInfoBotsValue: "🔧 Automation",
    serverInfoBoostField: "🚀 **Boost Status**",
    serverInfoBoostText: "Boosts",
    serverInfoLevelText: "Level",
    serverInfoTierText: "Tier",
    serverInfoCategoriesField: "📂 **Categories**",
    serverInfoCategoriesValue: "📊 Organization",
    serverInfoTextField: "💬 **Text Channels**",
    serverInfoTextValue: "📝 Communication",
    serverInfoVoiceField: "🔊 **Voice Channels**",
    serverInfoVoiceValue: "🎤 Audio",
    serverInfoRolesField: "🎭 **Total Roles**",
    serverInfoRolesValue: "🛡️ Hierarchy",
    serverInfoEmojisField: "😀 **Custom Emojis**",
    serverInfoEmojisValue: "🎨 Expression",
    serverInfoCreatedField: "🆕 **Server Created**",
    serverInfoFooter: "📊 Page {page} of {total} • Advanced Analytics",
    serverInfoPreviousButton: "◀️ Previous",
    serverInfoNextButton: "Next ▶️",

    // Server Icon command
    serverIconTitle: "🖼️ **SERVER ICON**",
    serverIconEmbedDescription: `\`\`\`\n🖼️ ICON GALLERY\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\`\n\n🏰 **{serverName}**\n\n🔗 **[Download Original]({iconURL})**\n\n\`\`\`yaml\nImage Details:\n  Format: High Quality PNG\n  Resolution: 1024x1024\n  Type: {imageType}\n\`\`\``,
    serverIconNoIconDescription: `\`\`\`\n🖼️ ICON DISPLAY\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\`\n\n❌ **No server icon found**\n\n\`\`\`yaml\nSuggestion:\n  Upload a server icon in Server Settings\n  Recommended: 512x512 pixels\n  Formats: PNG, JPG, GIF\n\`\`\``,
    serverIconAnimated: "Animated",
    serverIconStatic: "Static",
    serverIconFooter: "🎨 Server Icon • {memberCount} members",

    // Server Banner command
    serverBannerTitle: "🎨 **SERVER BANNER**",
    serverBannerEmbedDescription: `\`\`\`\n🎨 BANNER SHOWCASE\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\`\n\n🏰 **{serverName}**\n\n🔗 **[Download Original]({bannerURL})**\n\n\`\`\`yaml\nBanner Details:\n  Format: High Quality PNG\n  Resolution: 1920x1080\n  Boost Level: {boostLevel}\n  Status: Premium Feature\n\`\`\``,
    serverBannerNoBannerDescription: `\`\`\`\n🎨 BANNER DISPLAY\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\`\n\n❌ **No server banner found**\n\n\`\`\`yaml\nRequirements:\n  Boost Level: 2 or higher required\n  Current Level: {currentLevel}\n  Needed Boosts: {neededBoosts}\n\`\`\`\n\n> 🚀 **Boost this server to unlock banners!**`,
    serverBannerFooter: "🎨 Server Banner • Level {boostLevel} Boosted",

    // Server Membercount command
    serverMembercountTitle: "👥 **MEMBER ANALYTICS**",
    serverMembercountEmbedDescription: `\`\`\`\n👥 COMMUNITY STATISTICS\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\``,
    serverMembercountTotalField: "📊 **Total Members**",
    serverMembercountTotalValue: "🌐 Community",
    serverMembercountHumansField: "👤 **Human Users**",
    serverMembercountHumansValue: "🧑‍🤝‍🧑 Real People",
    serverMembercountBotsField: "🤖 **Bot Users**",
    serverMembercountBotsValue: "⚙️ Automation",
    serverMembercountOnlineField: "🟢 **Online**",
    serverMembercountOnlineValue: "✅ Active",
    serverMembercountIdleField: "🌙 **Idle**",
    serverMembercountIdleValue: "⏰ Away",
    serverMembercountDndField: "🔴 **Do Not Disturb**",
    serverMembercountDndValue: "🚫 Busy",
    serverMembercountOfflineField: "⚪ **Offline**",
    serverMembercountOfflineValue: "💤 Inactive",
    serverMembercountFooter: "📈 Member Analytics • {percentage}% Human Ratio",

    // Server Roles command
    serverRolesTitle: "🎭 **ROLE HIERARCHY**",
    serverRolesEmbedDescription: `\`\`\`\n🎭 PERMISSION STRUCTURE\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\``,
    serverRolesMembersText: "members",
    serverRolesNoneFound: "`No custom roles found`",
    serverRolesStats: `\`\`\`yaml\nStatistics:\n  Total Roles: {total}\n  Highest Role: {highest}\n  Most Members: {mostMembers}\n\`\`\``,
    serverRolesNone: "None",
    serverRolesFooter: "🎭 Page {page} of {total} • Role Management",
    
    // Server Roles Management
    serverRolesManagementTitle: "🎭 **ROLE MANAGEMENT** [{count}]",
    serverRolesManagementDescription: `\`\`\`\n🎭 HIERARCHY SYSTEM\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\``,
    serverRolesListMembersText: "members",
    serverRolesManagementStats: `\`\`\`yaml\nRole Statistics:\n  Total Roles: {total}\n  Hoisted Roles: {hoisted}\n  Mentionable: {mentionable}\n  With Permissions: {withPermissions}\n\`\`\``,
    serverRolesManagementFooter: "🎭 Role Hierarchy • {count} Total Roles",

    // Server Emojis command
    serverEmojisTitle: "😀 **EMOJI COLLECTION** ({current}/{total})",
    serverEmojisEmbedDescription: `\`\`\`\n😀 EMOJI LIBRARY\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\``,
    serverEmojisStats: `\`\`\`yaml\nCollection Stats:\n  Total Emojis: {total}\n  Animated: {animated}\n  Static: {static}\n  Page: {currentPage}/{totalPages}\n\`\`\``,
    serverEmojisFooter: "😀 Page {page} of {total} • Emoji Manager",
    
    // Server Emojis Collection
    serverEmojisCollectionTitle: "😀 **EMOJI COLLECTION**",
    serverEmojisCollectionDescription: `\`\`\`\n😀 EMOJI LIBRARY\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\``,
    serverEmojisAnimatedField: "🎞️ **Animated Emojis**",
    serverEmojisStaticField: "🖼️ **Static Emojis**",
    serverEmojisNone: "None",
    serverEmojisNoAnimated: "`No animated emojis`",
    serverEmojisNoStatic: "`No static emojis`",
    serverEmojisCollectionFooter: "😀 Emoji Collection • {total} Total ({animated} animated, {static} static)",

    // Server Channels command
    serverChannelsTitle: "📚 **CHANNEL OVERVIEW**",
    serverChannelsEmbedDescription: `\`\`\`\n📚 CHANNEL INFRASTRUCTURE\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\``,
    serverChannelsCategoriesField: "📂 **Categories**",
    serverChannelsCategoriesValue: "🗂️ Organization",
    serverChannelsTextField: "💬 **Text Channels**",
    serverChannelsTextValue: "📝 Discussion",
    serverChannelsVoiceField: "🔊 **Voice Channels**",
    serverChannelsVoiceValue: "🎤 Audio Chat",
    serverChannelsStageField: "🎭 **Stage Channels**",
    serverChannelsStageValue: "🎪 Presentations",
    serverChannelsThreadsField: "🧵 **Active Threads**",
    serverChannelsThreadsValue: "💭 Discussions",
    serverChannelsNewsField: "📰 **News Channels**",
    serverChannelsNewsValue: "📢 Announcements",
    serverChannelsForumField: "🏛️ **Forum Channels**",
    serverChannelsForumValue: "💬 Q&A",
    serverChannelsFooter: "📚 Channel System • {total} Total Channels",

    // Server Boosts command
    serverBoostsTitle: "🚀 **BOOST ANALYTICS**",
    serverBoostsEmbedDescription: `\`\`\`\n🚀 BOOST DASHBOARD\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\``,
    serverBoostsCurrentField: "💎 **Current Level**",
    serverBoostsActiveField: "🚀 **Active Boosts**",
    serverBoostsActiveValue: "💝 Supporters",
    serverBoostsNextField: "📈 **Next Level**",
    serverBoostsMoreNeeded: "more needed",
    serverBoostsTarget: "🎯 Target",
    serverBoostsMaxLevel: "`Max Level Reached`\n🏆 Elite Status",
    serverBoostsPerksField: "🎁 **Level {level} Perks**",
    serverBoostsThumbnail: "https://cdn.discordapp.com/emojis/853314249405071390.gif",
    serverBoostsFooter: "🚀 Boost System • Learn more: discord.com/nitro",

    // Boost perks by level
    serverBoostPerks: {
        0: ["📱 Mobile streaming", "🎧 Voice quality: 96kbps"],
        1: ["🎬 Screen sharing: 720p 60fps", "📊 Custom emoji: 50 total", "🎧 Voice quality: 128kbps"],
        2: ["🎬 Screen sharing: 1080p 60fps", "📊 Custom emoji: 100 total", "🎨 Server banner", "📁 Upload limit: 50MB"],
        3: ["🎬 Screen sharing: 4K 60fps", "📊 Custom emoji: 250 total", "🎨 Animated server icon", "📁 Upload limit: 100MB", "🎵 Custom invite background"]
    },

    // Server Region command
    serverRegionTitle: "🌍 **SERVER REGION**",
    serverRegionEmbedDescription: `\`\`\`\n🌍 REGIONAL SETTINGS\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\`\n\n🗺️ **Preferred Locale:** \`{locale}\`\n\n\`\`\`yaml\nRegion Benefits:\n  🌐 Optimized connections\n  📊 Localized features\n  🎯 Targeted content\n  ⚡ Reduced latency\n\`\`\`\n\n> 🔧 **Admins can change this in Server Settings**`,
    serverRegionFooter: "🌍 Server Region • {memberCount} global members",
    serverRegionDefaultLocale: "English (US)",

    // Server Verification command
    serverVerificationTitle: "🔐 **VERIFICATION SYSTEM**",
    serverVerificationEmbedDescription: `\`\`\`\n🔐 SECURITY DASHBOARD\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\``,
    serverVerificationCurrentField: "🛡️ **Current Level**",
    serverVerificationRequirementsField: "📋 **Requirements**",
    serverVerificationProtectionField: "🎯 **Protection**",
    serverVerificationLevelsField: "📊 **Verification Levels**",
    serverVerificationSecurityText: "🔧 Security",
    serverVerificationActiveText: "✅ Active",
    serverVerificationEnhancedText: "Enhanced Security",
    serverVerificationNoRestrictions: "No restrictions",
    serverVerificationEmailVerification: "Email verification",
    serverVerificationAccountAge: "Account age required",
    serverVerificationMemberDuration: "Member duration required",
    serverVerificationPhoneVerification: "Phone verification",
    serverVerificationFooter: "🔐 Verification System • {level} Level Active",

    // Verification levels
    serverVerificationLevels: {
        0: { name: "None", desc: "No verification required", emoji: "🔓", color: "#95a5a6" },
        1: { name: "Low", desc: "Email verification required", emoji: "📧", color: "#3498db" },
        2: { name: "Medium", desc: "Account age > 5 minutes", emoji: "⏰", color: "#f39c12" },
        3: { name: "High", desc: "Member for 10+ minutes", emoji: "🔒", color: "#e74c3c" },
        4: { name: "Very High", desc: "Phone number required", emoji: "📱", color: "#8e44ad" }
    },

    // Server Features command
    serverFeaturesTitle: "🛠️ **SERVER FEATURES**",
    serverFeaturesEmbedDescription: `\`\`\`\n🛠️ FEATURE DASHBOARD\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\``,
    serverFeaturesEnabledField: "🎯 **Enabled Features**",
    serverFeaturesNoneEnabled: "`No special features enabled`",
    serverFeaturesCountField: "📊 **Feature Count**",
    serverFeaturesCountValue: "🔧 Total Features",
    serverFeaturesCustomizationField: "🎨 **Customization**",
    serverFeaturesCustomizationValue: "🖌️ Visual Features",
    serverFeaturesSecurityField: "🛡️ **Security**",
    serverFeaturesSecurityValue: "🔒 Safety Features",
    serverFeaturesFooter: "🛠️ Server Features • {count} Active Features",

    // Feature descriptions
    serverFeatureDescriptions: {
        'ANIMATED_BANNER': '🎬 Animated Banner',
        'ANIMATED_ICON': '🎭 Animated Icon',
        'APPLICATION_COMMAND_PERMISSIONS_V2': '⚙️ Advanced Permissions',
        'AUTO_MODERATION': '🤖 Auto Moderation',
        'BANNER': '🎨 Server Banner',
        'COMMUNITY': '🌐 Community Server',
        'DEVELOPER_SUPPORT_SERVER': '👨‍💻 Developer Support',
        'DISCOVERABLE': '🔍 Server Discovery',
        'FEATURABLE': '⭐ Featurable',
        'INVITES_DISABLED': '🚫 Invites Disabled',
        'INVITE_SPLASH': '🌊 Invite Splash',
        'MEMBER_VERIFICATION_GATE_ENABLED': '🔐 Member Screening',
        'MORE_EMOJI': '😀 Extended Emojis',
        'NEWS': '📰 News Channels',
        'PARTNERED': '🤝 Discord Partner',
        'PREVIEW_ENABLED': '👁️ Server Preview',
        'PRIVATE_THREADS': '🧵 Private Threads',
        'ROLE_ICONS': '🎭 Role Icons',
        'THREADS_ENABLED': '💬 Threads Enabled',
        'THREE_DAY_THREAD_ARCHIVE': '📦 3-Day Thread Archive',
        'TICKETED_EVENTS_ENABLED': '🎟️ Ticketed Events',
        'VANITY_URL': '🔗 Vanity URL',
        'VERIFIED': '✅ Verified Server',
        'VIP_REGIONS': '🌍 VIP Voice Regions',
        'WELCOME_SCREEN_ENABLED': '👋 Welcome Screen'
    },

    // Server Help command
    serverHelpTitle: "🏰 **SERVER COMMAND HELP**",
    serverHelpEmbedDescription: `\`\`\`\n🏰 COMMAND NAVIGATION\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\``,
    serverHelpInformationField: "📊 **Information**",
    serverHelpInformationValue: "`/server info` - Detailed server overview\n`/server membercount` - Member analytics\n`/server verification` - Security settings",
    serverHelpVisualField: "🎨 **Visual**",
    serverHelpVisualValue: "`/server icon` - Server icon display\n`/server banner` - Server banner view\n`/server emojis` - Emoji collection",
    serverHelpManagementField: "⚙️ **Management**",
    serverHelpManagementValue: "`/server roles` - Role hierarchy\n`/server channels` - Channel overview\n`/server features` - Server capabilities",
    serverHelpPremiumField: "🚀 **Premium**",
    serverHelpPremiumValue: "`/server boosts` - Boost information\n`/server region` - Server locale\n`/server features` - Premium features",
    serverHelpFooter: "🏰 Server Tools • {serverName}",
};
