const { SlashCommandBuilder, EmbedBuilder } = require('discord.js');

module.exports = {
    // Main user command
    userDescription: "Advanced user profile and analytics tools.",
    
    // Subcommand descriptions and options
    userPermissionsDescription: "Detailed channel permissions analysis.",
    userPermissionsChannelOption: "Channel to analyze",
    userPermissionsTargetOption: "Target user",
    userMutualsDescription: "Mutual servers analysis.",
    userMutualsTargetOption: "Target user",
    userNicknameDescription: "Nickname management (Admin only).",
    userNicknameActionOption: "Action to perform",
    userNicknameTargetOption: "Target user",
    userNicknameViewChoice: "view",
    userNicknameResetChoice: "reset",
    userInfoDescription: "Comprehensive user information and analytics.",
    userInfoTargetOption: "Target user to analyze",
    userAvatarDescription: "Display user avatar in high resolution.",
    userAvatarTargetOption: "Target user",
    userBannerDescription: "Show user profile banner.",
    userBannerTargetOption: "Target user",
    userRolesDescription: "Analyze user roles and permissions.",
    userRolesTargetOption: "Target user",
    userJoinedatDescription: "Server join date and member analytics.",
    userJoinedatTargetOption: "Target user",
    userBadgesDescription: "Discord badges and achievements.",
    userBadgesTargetOption: "Target user",
    userCreatedatDescription: "Account creation date and age.",
    userCreatedatTargetOption: "Target user",
    userBoostingDescription: "Server boost status and history.",
    userBoostingTargetOption: "Target user",
    userActivityDescription: "User activity and presence status.",
    userActivityTargetOption: "Target user",
    userSecurityDescription: "Account security analysis.",
    userSecurityTargetOption: "Target user",
    userStatsDescription: "Advanced user statistics.",
    userStatsTargetOption: "Target user",

    // Colors
    userInfoColor: "#00d4ff",
    userAvatarColor: "#7c3aed",
    userBannerColor: "#00ff88",
    userBannerDefaultColor: "#00ff88",
    userRolesColor: "#8e44ad",
    userPermissionsColor: "#3498db",
    userPermissionsErrorColor: "#ff0000",
    userJoinedatColor: "#2ecc71",
    userJoinedatErrorColor: "#ff0000",
    userBadgesColor: "#f1c40f",
    userCreatedatColor: "#2d98da",
    userBoostingColor: "#e84393",
    userMutualsColor: "#1abc9c",
    userActivityColor: "#9b59b6",
    userNicknameColor: "#34495e",
    userNicknameAccessDeniedColor: "#ff0000",
    userNicknameResetSuccessColor: "#00ff00",
    userNicknameResetErrorColor: "#ff0000",
    userSecurityLowRiskColor: "#00ff00",
    userSecurityMediumRiskColor: "#ffff00",
    userSecurityHighRiskColor: "#ff0000",
    userStatsColor: "#16a085",
    userHelpColor: "#3498db",
    userUnknownErrorColor: "#ff0000",

    // User Info command
    userInfoTitle: "🔍 **USER PROFILE ANALYSIS**",
    userInfoEmbedDescription: `\`\`\`\n🔍 IDENTITY SCANNER\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\``,
    userInfoIdentityField: "👤 **Identity**",
    userInfoIdentityValue: "**Tag:** `{tag}`\n**ID:** `{id}`\n**Type:** {type}",
    userInfoTimelineField: "📅 **Timeline**",
    userInfoTimelineValue: "**Created:** {accountAge}\n**Joined:** {serverAge}\n**Position:** #{position}",
    userInfoStatusField: "⚡ **Status**",
    userInfoStatusValue: "**Presence:** {presence}\n**Activity:** {activity}\n**Boost:** {boost}",
    userInfoServerProfileField: "🏆 **Server Profile**",
    userInfoServerProfileValue: "**Highest Role:** {highestRole}\n**Role Count:** {roleCount}\n**Permissions:** {permissions}",
    userInfoRolesField: "🎭 **Roles**",
    userInfoBot: "🤖 Bot",
    userInfoUser: "👨‍💻 User",
    userInfoNone: "None",
    userInfoBoostYes: "💎 Yes",
    userInfoBoostNo: "❌ No",
    userInfoAdmin: "🔑 Admin",
    userInfoMember: "👤 Member",
    userInfoNotInServer: "Not in server",
    userInfoNotAvailable: "N/A",
    userInfoNoRoles: "No roles",
    userInfoMoreRoles: "more",
    userInfoFooter: "🔍 Profile scanned by {sender}",

    // User Avatar command
    userAvatarTitle: "🖼️ **AVATAR DISPLAY**",
    userAvatarEmbedDescription: `\`\`\`\n🖼️ AVATAR VIEWER\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\`\n\n**User:** {tag}\n**Resolution:** 1024x1024px\n**Format:** {format}\n\n🔗 **[Download Avatar]({avatarURL})**`,
    userAvatarAnimated: "GIF (Animated)",
    userAvatarStatic: "PNG (Static)",
    userAvatarFooter: "🎨 Avatar requested by {sender}",

    // User Banner command
    userBannerTitle: "🌟 **PROFILE BANNER**",
    userBannerEmbedDescription: `\`\`\`\n🌟 BANNER VIEWER\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\`\n\n**User:** {tag}\n**Accent Color:** {accentColor}\n**Banner Status:** {bannerStatus}\n\n{bannerText}`,
    userBannerDefault: "Default",
    userBannerAvailable: "✅ Available",
    userBannerNotSet: "❌ Not Set",
    userBannerDownload: "🔗 **[Download Banner]({banner})**",
    userBannerNotSetText: "💡 *User has not set a custom banner*",
    userBannerFooter: "🎨 Banner requested by {sender}",

    // User Roles command
    userRolesTitle: "🎭 **ROLE ANALYSIS**",
    userRolesEmbedDescription: `\`\`\`\n🎭 ROLE HIERARCHY\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\`\n\n**Target:** {tag}\n**Total Roles:** {totalRoles}\n**Highest Role:** {highestRole}\n**Role Color:** {roleColor}\n\n**📋 Role List:**\n{roleList}`,
    userRolesNoRoles: "No roles assigned",
    userRolesNone: "None",
    userRolesFooter: "🎭 Roles analyzed by {sender}",

    // User Permissions command
    userPermissionsTitle: "🔐 **PERMISSION ANALYSIS**",
    userPermissionsEmbedDescription: `\`\`\`\n🔐 CHANNEL PERMISSIONS\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\`\n\n**Channel:** {channelName}\n**User:** {tag}\n**Total Permissions:** {totalPermissions}`,
    userPermissionsAdminField: "🔑 **Admin Permissions**",
    userPermissionsModerationField: "🛡️ **Moderation Permissions**",
    userPermissionsBasicField: "📝 **Basic Permissions**",
    userPermissionsNone: "None",
    userPermissionsMore: "more",
    userPermissionsFooter: "🔐 Permissions analyzed by {sender}",
    userPermissionsErrorTitle: "❌ **ERROR**",
    userPermissionsErrorDescription: "Please specify a valid channel!",

    // User Joinedat command
    userJoinedatTitle: "📅 **JOIN DATE ANALYSIS**",
    userJoinedatEmbedDescription: `\`\`\`\n📅 MEMBERSHIP TIMELINE\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\`\n\n**User:** {tag}\n**Join Date:** <t:{joinTimestamp}:F>\n**Time Ago:** {joinAge}\n**Days Active:** {daysSinceJoin}\n**Join Position:** #{joinPosition}\n\n**🏆 Member Status:**\n{memberStatus}`,
    userJoinedatVeteran: "🌟 Veteran Member",
    userJoinedatExperienced: "💎 Experienced Member",
    userJoinedatActive: "🔥 Active Member",
    userJoinedatNew: "🌱 New Member",
    userJoinedatFooter: "📅 Join date checked by {sender}",
    userJoinedatErrorTitle: "❌ **ERROR**",
    userJoinedatErrorDescription: "User is not in this server!",

    // User Badges command
    userBadgesTitle: "🏅 **BADGE COLLECTION**",
    userBadgesEmbedDescription: `\`\`\`\n🏅 ACHIEVEMENT SYSTEM\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\`\n\n**User:** {tag}\n**Badge Count:** {badgeCount}\n**Profile Status:** {profileStatus}\n\n**🏆 Badge Collection:**\n{badgeCollection}\n\n> 💡 **Tip:** Badges are earned through Discord achievements and contributions!`,
    userBadgesDistinguished: "🌟 Distinguished",
    userBadgesStandard: "👤 Standard",
    userBadgesNoBadges: "📝 No badges earned yet",
    userBadgesFooter: "🏅 Badges viewed by {sender}",

    // Badge emojis
    userBadgeEmojis: {
        'Staff': '👑',
        'Partner': '🤝',
        'Hypesquad': '🎉',
        'BugHunterLevel1': '🐛',
        'BugHunterLevel2': '🐛',
        'HypesquadOnlineHouse1': '🏠',
        'HypesquadOnlineHouse2': '🏠',
        'HypesquadOnlineHouse3': '🏠',
        'PremiumEarlySupporter': '💎',
        'TeamPseudoUser': '🤖',
        'VerifiedBot': '✅',
        'VerifiedDeveloper': '🔨',
        'CertifiedModerator': '🛡️',
        'BotHTTPInteractions': '🔗',
        'ActiveDeveloper': '⚡'
    },

    // User Createdat command
    userCreatedatTitle: "🎂 **ACCOUNT CREATION**",
    userCreatedatEmbedDescription: `\`\`\`\n🎂 ACCOUNT TIMELINE\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\`\n\n**User:** {tag}\n**Created:** <t:{createdTimestamp}:F>\n**Age:** {accountAge}\n**Days Old:** {daysSinceCreation}\n**Account Status:** {accountStatus}\n\n**📊 Account Metrics:**\n• **Years Active:** {yearsActive}\n• **Months Active:** {monthsActive}\n• **Experience Level:** {experienceLevel}`,
    userCreatedatVeteran: "🌟 Veteran Account",
    userCreatedatMature: "💎 Mature Account",
    userCreatedatEstablished: "🔥 Established Account",
    userCreatedatNew: "🌱 New Account",
    userCreatedatExpert: "Expert",
    userCreatedatAdvanced: "Advanced",
    userCreatedatIntermediate: "Intermediate",
    userCreatedatBeginner: "Beginner",
    userCreatedatFooter: "🎂 Account age checked by {sender}",

    // User Boosting command
    userBoostingTitle: "🚀 **BOOST ANALYSIS**",
    userBoostingEmbedDescription: `\`\`\`\n🚀 NITRO BOOST STATUS\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\`\n\n**User:** {tag}\n**Boost Status:** {boostStatus}\n**Server Level:** {serverLevel}\n**Total Boosts:** {totalBoosts}\n\n{boostDetails}`,
    userBoostingActive: "💎 Active Booster",
    userBoostingNotBoosting: "❌ Not Boosting",
    userBoostingLevel: "Level",
    userBoostingNoLevel: "No Level",
    userBoostingDetails: "**🎉 Boost Details:**\n• **Started:** {boostDuration}\n• **Duration:** <t:{boostTimestamp}:R>\n• **Contribution:** Server Enhancement\n• **Benefits:** Exclusive perks unlocked",
    userBoostingBenefits: "**💡 Boost Benefits:**\n• Higher audio quality\n• Custom server emoji\n• Enhanced upload limits\n• Priority support",
    userBoostingFooter: "🚀 Boost status checked by {sender}",

    // User Mutuals command
    userMutualsTitle: "🌐 **MUTUAL SERVERS**",
    userMutualsEmbedDescription: `\`\`\`\n🌐 NETWORK ANALYSIS\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\`\n\n**User:** {tag}\n**Mutual Servers:** {mutualCount}\n**Network Reach:** {networkReach} total members\n\n**🏰 Shared Servers:**\n{sharedServers}\n\n> 🔍 **Network Score:** {networkScore}`,
    userMutualsMembersText: "members",
    userMutualsMoreServers: "more servers",
    userMutualsNoMutuals: "No mutual servers found",
    userMutualsHigh: "High",
    userMutualsMedium: "Medium",
    userMutualsLow: "Low",
    userMutualsFooter: "🌐 Network scanned by {sender}",

    // User Activity command
    userActivityTitle: "⚡ **ACTIVITY MONITOR**",
    userActivityEmbedDescription: `\`\`\`\n⚡ PRESENCE TRACKER\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\`\n\n**User:** {tag}\n**Status:** {statusEmoji} {status}\n**Activities:** {activitiesCount}\n**Platform:** {platform}\n\n**🎮 Current Activities:**\n{currentActivities}`,
    userActivityStatusEmojis: {
        'online': '🟢',
        'idle': '🟡',
        'dnd': '🔴',
        'offline': '⚫'
    },
    userActivityUnknown: "Unknown",
    userActivityPlaying: "🎮 Playing",
    userActivityStreaming: "📺 Streaming",
    userActivityListening: "🎵 Listening",
    userActivityWatching: "👀 Watching",
    userActivityCustom: "📝 Custom",
    userActivityCompeting: "🏆 Competing",
    userActivityUnknownType: "❓ Unknown",
    userActivityNoStatus: "💤 No active status",
    userActivityFooter: "⚡ Activity checked by {sender}",

    // User Nickname command
    userNicknameTitle: "🏷️ **NICKNAME MANAGER**",
    userNicknameEmbedDescription: `\`\`\`\n🏷️ NICKNAME SYSTEM\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\`\n\n**User:** {tag}\n**Current Nickname:** {nickname}\n**Display Name:** {displayName}\n**Can Modify:** {canModify}\n\n**🔧 Management Options:**\n• Use \`reset\` action to clear nickname\n• Check role hierarchy for permissions\n• Nickname history is not tracked`,
    userNicknameNoNickname: "No nickname set",
    userNicknameCanModifyYes: "✅ Yes",
    userNicknameCanModifyNo: "❌ No",
    userNicknameFooter: "🏷️ Nickname managed by {sender}",
    userNicknameAccessDeniedTitle: "❌ **ACCESS DENIED**",
    userNicknameAccessDeniedDescription: "🔒 You need `Manage Nicknames` permission to use this command!",
    userNicknameResetSuccessTitle: "✅ **NICKNAME RESET**",
    userNicknameResetSuccessDescription: "Successfully reset {tag}'s nickname!",
    userNicknameResetErrorTitle: "❌ **ERROR**",
    userNicknameResetErrorDescription: "Failed to reset nickname. Check role hierarchy!",

    // User Security command
    userSecurityTitle: "🔐 **SECURITY ANALYSIS**",
    userSecurityEmbedDescription: `\`\`\`\n🔐 ACCOUNT SECURITY\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\`\n\n**User:** {tag}\n**Security Score:** {securityScore}/100\n**Risk Level:** {riskLevel}\n\n**🔍 Security Factors:**\n• **Account Age:** {accountAgeStatus} {accountAge} days\n• **Profile Picture:** {avatarStatus} {avatarText}\n• **Discord Badges:** {badgesStatus} {badgeCount} badges\n• **Verification:** {verificationStatus} {verificationType}\n\n**🛡️ Risk Assessment:**\n{riskAssessment}`,
    userSecurityLowRisk: "🟢 Low",
    userSecurityMediumRisk: "🟡 Medium",
    userSecurityHighRisk: "🔴 High",
    userSecurityAvatarSet: "Set",
    userSecurityAvatarDefault: "Default",
    userSecurityVerified: "Verified",
    userSecurityStandard: "Standard",
    userSecurityLowRiskAssessment: "🟢 **LOW RISK** - Established account",
    userSecurityMediumRiskAssessment: "🟡 **MEDIUM RISK** - Moderate verification",
    userSecurityHighRiskAssessment: "🔴 **HIGH RISK** - Limited account history",
    userSecurityFooter: "🔐 Security scanned by {sender}",

    // User Stats command
    userStatsTitle: "📊 **ADVANCED STATISTICS**",
    userStatsEmbedDescription: `\`\`\`\n📊 COMPREHENSIVE ANALYTICS\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\`\n\n**User:** {tag}\n**Overall Score:** {overallScore}`,
    userStatsAccountMetricsField: "📈 **Account Metrics**",
    userStatsAccountMetricsValue: "• Account Age: {accountAge} days\n• Server Time: {serverAge} days\n• Total Badges: {badgeCount}\n• Bot Status: {botStatus}",
    userStatsServerProfileField: "🎭 **Server Profile**",
    userStatsServerProfileValue: "• Role Count: {roleCount}\n• Highest Role: {highestRole}\n• Boost Status: {boostStatus}\n• Join Position: Computing...",
    userStatsNetworkDataField: "🌐 **Network Data**",
    userStatsNetworkDataValue: "• Mutual Servers: {mutualCount}\n• Network Reach: {networkReach}\n• Presence: {presence}\n• Platform: {platform}",
    userStatsNotInServer: "Not in server",
    userStatsYes: "Yes",
    userStatsNo: "No",
    userStatsActive: "Active",
    userStatsNone: "None",
    userStatsUnknown: "Unknown",
    userStatsFooter: "📊 Statistics compiled by {sender}",

    // User Help command
    userHelpTitle: "🔍 **USER COMMAND HELP**",
    userHelpEmbedDescription: `\`\`\`\n🔍 ADVANCED USER TOOLS\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\`\n\n**📋 Available Commands:**\nUse \`{prefix} <subcommand>\` or \`{prefix} <subcommand>\``,
    userHelpProfileField: "📊 **Profile Commands**",
    userHelpProfileValue: "• `info` - Complete user profile analysis\n• `avatar` - High-resolution avatar display\n• `banner` - Profile banner viewer\n• `createdat` - Account creation timeline\n• `badges` - Discord achievements",
    userHelpServerField: "🏰 **Server Commands**",
    userHelpServerValue: "• `roles` - Role hierarchy analysis\n• `permissions` - Channel permissions\n• `joinedat` - Server join analytics\n• `boosting` - Boost status tracker\n• `nickname` - Nickname management (Admin)",
    userHelpNetworkField: "🌐 **Network Commands**",
    userHelpNetworkValue: "• `mutuals` - Mutual server analysis\n• `activity` - Presence monitoring\n• `security` - Account security scan\n• `stats` - Advanced statistics\n• `help` - This command guide",
    userHelpUsageField: "💡 **Usage Examples**",
    userHelpUsageValue: "• `/user info @username` - Analyze user profile\n• `/user permissions @user #channel` - Check permissions\n• `/user mutuals @user` - View mutual servers\n• `/user security` - Scan your account security",
    userHelpFeaturesField: "🔧 **Features**",
    userHelpFeaturesValue: "• **Hybrid Support** - Works with slash commands and prefix\n• **Advanced Analytics** - Comprehensive user insights\n• **Permission Checks** - Detailed permission analysis\n• **Security Scanning** - Account safety assessment\n• **Network Mapping** - Mutual server discovery",
    userHelpFooter: "🔍 Help requested by {sender} | Version 2.0",

    // Error messages
    userUnknownErrorTitle: "❌ **UNKNOWN COMMAND**",
    userUnknownErrorDescription: "Unknown subcommand: `{subcommand}`\n\nUse `[prefix ex: !user help]` to see all available commands.",
};
